name: 'Secret Scanning Review'
on: [pull_request]

jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dependency Review'
        uses: felickz/secret-scanning-review-action@v0
        env:
            GITHUB_TOKEN: ${{ secrets.SECRET_SCAN_REVIEW_GITHUB_TOKEN }}
            SSR_FAIL_ON_ALERT: true
            SSR_FAIL_ON_ALERT_EXCLUDE_CLOSED: true
